name: Robot Tests
on: [pull_request]
jobs:
  functional-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install robotframework robotframework-requests
      - run: robot tests/robot/functional
      - run: robot tests/robot/e2e
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install robotframework robotframework-requests
      - run: robot tests/robot/security
